query GetAllPost {
  getAllPost {
    _id
    creatorId
    title
    tags
    picUrl
    description
    likes
    comments
    createdAt
    updatedAt
    User {
      _id
      name
      email
    }
  }
}
